name: Close stale PRs, ISSUEs

on:
  schedule:
    - cron: "0 3 * * 1-5" # Asia/Seoul(UTC+9) 월 화 수 목 금 오전 12시에 실행
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  close_prs_issues:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge and Close stale PRs
        run: |
          prs=$(gh pr list --state open --json number --jq '.[].number')
          for pr in $prs; do
            gh pr merge $pr --merge -c "Automatically merge stale #$pr."
            gh pr close $pr -c "Automatically close stale #$pr."
          done
      - name: Push changes to main branch
        run: |
          git push origin main
      - name: Close stale Issues
        run: |
          gh issue list --state open --json number --jq '.[].number' | while read -r issue; do
            gh issue close $issue -c "Automatically closing stale issue."
          done

